# Project information
site_name: GMEM
site_url: http://gmem.tech
site_author: dev@openeuler.org

# Repository
repo_name: openEuler/libgmem
repo_url: https://gitee.com/openeuler/libgmem
edit_uri: https://gitee.com/openeuler/libgmem/tree/master/docs

# Copyright
copyright: Copyright &copy; 2023 openEuler GMEM team

# Pages
nav:
- Home: index.md

theme:
  name: mkdocs
